// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm24nTLziYEUCub9-6zrquec0VOGIZalU',
    appId: '1:269766392914:web:d2578f1ac5f079f91df38b',
    messagingSenderId: '269766392914',
    projectId: 'chat-app-59f82',
    authDomain: 'chat-app-59f82.firebaseapp.com',
    storageBucket: 'chat-app-59f82.firebasestorage.app',
    measurementId: 'G-PYT5F5B93W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7vu9bUPqv_gGvk3y7-sE3eTM0nlsohVk',
    appId: '1:269766392914:android:6560be7f95f9a9361df38b',
    messagingSenderId: '269766392914',
    projectId: 'chat-app-59f82',
    storageBucket: 'chat-app-59f82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFWlMVqFpL7sLgbys_SekGYg_VO6CEuwc',
    appId: '1:269766392914:ios:9c4348926500263b1df38b',
    messagingSenderId: '269766392914',
    projectId: 'chat-app-59f82',
    storageBucket: 'chat-app-59f82.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFWlMVqFpL7sLgbys_SekGYg_VO6CEuwc',
    appId: '1:269766392914:ios:9c4348926500263b1df38b',
    messagingSenderId: '269766392914',
    projectId: 'chat-app-59f82',
    storageBucket: 'chat-app-59f82.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm24nTLziYEUCub9-6zrquec0VOGIZalU',
    appId: '1:269766392914:web:ede5a3731be05e9d1df38b',
    messagingSenderId: '269766392914',
    projectId: 'chat-app-59f82',
    authDomain: 'chat-app-59f82.firebaseapp.com',
    storageBucket: 'chat-app-59f82.firebasestorage.app',
    measurementId: 'G-P628E6PRCD',
  );
}
